import configparser
import os
import shutil
import sys
from pathlib import Path
from typing import Any, Dict

from helper_file import FileHelper


# def get_resource_path(relative_path: str) -> Path:
#     if getattr(sys, 'frozen', False):
#         base_path = Path(sys._MEIPASS)
#     else:
#         base_path = Path(__file__).parent.absolute()
#     return base_path / relative_path

def convert_mapping(pyinput_mapping: str) -> str:
    return pyinput_mapping.replace("<", "").replace(">", "").replace("\"", "")

class KgConfig:
    CONFIG_DIR = Path("~/.config/kitty-guake").expanduser()
    MAIN_CONF = CONFIG_DIR / "kitty-guake.conf"
    KITTY_BASE_CONF = CONFIG_DIR / "kitty.conf"
    KITTY_GEN_CONF = CONFIG_DIR / "generated.conf"

    KITTY_CONFIG_DIR = Path("~/.config/kitty").expanduser()
    KITTY_TAB_SCRIPT = KITTY_CONFIG_DIR / "tab_bar.py"

    def __init__(self):
        self.config: Dict[str, Any] = {}

    def init_config(self) -> None:
        self.CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        self.KITTY_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

        if not self.MAIN_CONF.exists():
            self._copy_template("kitty-guake.conf", self.MAIN_CONF)

        if not self.KITTY_BASE_CONF.exists():
            self._copy_template("kitty.conf", self.KITTY_BASE_CONF)

        if not self.KITTY_TAB_SCRIPT.exists():
            self._copy_template("tab_bar.py", self.KITTY_TAB_SCRIPT)

        self.config = self._read_conf_to_dict(self.MAIN_CONF)
        self.generate_kitty_conf()

    def generate_kitty_conf(self) -> None:
        if not self.KITTY_BASE_CONF.exists():
            return

        content = self.KITTY_BASE_CONF.read_text()

        hotkeys_cfg = self.config.get('hotkeys', {})
        if hotkeys_cfg.get("hotkey_automap") == "true":
            content += "\n\n#------------ GENERATED BY KITTY-GUAKE -------------"
            keys = [
                "hotkey_resize_up", "hotkey_resize_down",
                "hotkey_move_left", "hotkey_move_right",
                "hotkey_visibility_toggle"
            ]
            for key in keys:
                val = hotkeys_cfg.get(key)
                if val:
                    content += f"\nmap {convert_mapping(val)} discard_event"
            content += "\n#---------------------------------------------------\n"

        self.KITTY_GEN_CONF.write_text(content)

    def get_config_dir(self) -> Path:
        return self.CONFIG_DIR

    def _read_conf_to_dict(self, filepath: Path) -> Dict[str, Any]:
        config = configparser.ConfigParser()
        try:
            config.read(filepath)
        except Exception as e:
            print(f"Error reading config {filepath}: {e}")
            return {}

        result = {}
        for section in config.sections():
            result[section] = dict(config.items(section))
        return result

    def _copy_template(self, template_name: str, target_path: Path) -> None:
        template_path = FileHelper.get_resource_path(f"templates/{template_name}")
        if template_path.exists():
            shutil.copy2(template_path, target_path)
            print(f"Template copied to: {target_path}")
        else:
            print(f"Template not found: {template_path}")